// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nanopb.proto

package fi.kapsi.koti.jpa.nanopb;

public final class Nanopb {
  private Nanopb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbFileopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbEnumopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopb);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code FieldType}
   */
  public enum FieldType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Automatically decide field type, generate static field if possible.
     * </pre>
     *
     * <code>FT_DEFAULT = 0;</code>
     */
    FT_DEFAULT(0),
    /**
     * <pre>
     * Always generate a callback field.
     * </pre>
     *
     * <code>FT_CALLBACK = 1;</code>
     */
    FT_CALLBACK(1),
    /**
     * <pre>
     * Always generate a dynamically allocated field.
     * </pre>
     *
     * <code>FT_POINTER = 4;</code>
     */
    FT_POINTER(4),
    /**
     * <pre>
     * Generate a static field or raise an exception if not possible.
     * </pre>
     *
     * <code>FT_STATIC = 2;</code>
     */
    FT_STATIC(2),
    /**
     * <pre>
     * Ignore the field completely.
     * </pre>
     *
     * <code>FT_IGNORE = 3;</code>
     */
    FT_IGNORE(3),
    /**
     * <pre>
     * Legacy option, use the separate 'fixed_length' option instead
     * </pre>
     *
     * <code>FT_INLINE = 5;</code>
     */
    FT_INLINE(5),
    ;

    /**
     * <pre>
     * Automatically decide field type, generate static field if possible.
     * </pre>
     *
     * <code>FT_DEFAULT = 0;</code>
     */
    public static final int FT_DEFAULT_VALUE = 0;
    /**
     * <pre>
     * Always generate a callback field.
     * </pre>
     *
     * <code>FT_CALLBACK = 1;</code>
     */
    public static final int FT_CALLBACK_VALUE = 1;
    /**
     * <pre>
     * Always generate a dynamically allocated field.
     * </pre>
     *
     * <code>FT_POINTER = 4;</code>
     */
    public static final int FT_POINTER_VALUE = 4;
    /**
     * <pre>
     * Generate a static field or raise an exception if not possible.
     * </pre>
     *
     * <code>FT_STATIC = 2;</code>
     */
    public static final int FT_STATIC_VALUE = 2;
    /**
     * <pre>
     * Ignore the field completely.
     * </pre>
     *
     * <code>FT_IGNORE = 3;</code>
     */
    public static final int FT_IGNORE_VALUE = 3;
    /**
     * <pre>
     * Legacy option, use the separate 'fixed_length' option instead
     * </pre>
     *
     * <code>FT_INLINE = 5;</code>
     */
    public static final int FT_INLINE_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FieldType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FieldType forNumber(int value) {
      switch (value) {
        case 0: return FT_DEFAULT;
        case 1: return FT_CALLBACK;
        case 4: return FT_POINTER;
        case 2: return FT_STATIC;
        case 3: return FT_IGNORE;
        case 5: return FT_INLINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FieldType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FieldType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FieldType>() {
            public FieldType findValueByNumber(int number) {
              return FieldType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor().getEnumTypes().get(0);
    }

    private static final FieldType[] VALUES = values();

    public static FieldType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FieldType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FieldType)
  }

  /**
   * Protobuf enum {@code IntSize}
   */
  public enum IntSize
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Default, 32/64bit based on type in .proto
     * </pre>
     *
     * <code>IS_DEFAULT = 0;</code>
     */
    IS_DEFAULT(0),
    /**
     * <code>IS_8 = 8;</code>
     */
    IS_8(8),
    /**
     * <code>IS_16 = 16;</code>
     */
    IS_16(16),
    /**
     * <code>IS_32 = 32;</code>
     */
    IS_32(32),
    /**
     * <code>IS_64 = 64;</code>
     */
    IS_64(64),
    ;

    /**
     * <pre>
     * Default, 32/64bit based on type in .proto
     * </pre>
     *
     * <code>IS_DEFAULT = 0;</code>
     */
    public static final int IS_DEFAULT_VALUE = 0;
    /**
     * <code>IS_8 = 8;</code>
     */
    public static final int IS_8_VALUE = 8;
    /**
     * <code>IS_16 = 16;</code>
     */
    public static final int IS_16_VALUE = 16;
    /**
     * <code>IS_32 = 32;</code>
     */
    public static final int IS_32_VALUE = 32;
    /**
     * <code>IS_64 = 64;</code>
     */
    public static final int IS_64_VALUE = 64;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static IntSize valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static IntSize forNumber(int value) {
      switch (value) {
        case 0: return IS_DEFAULT;
        case 8: return IS_8;
        case 16: return IS_16;
        case 32: return IS_32;
        case 64: return IS_64;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<IntSize>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        IntSize> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<IntSize>() {
            public IntSize findValueByNumber(int number) {
              return IntSize.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor().getEnumTypes().get(1);
    }

    private static final IntSize[] VALUES = values();

    public static IntSize valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private IntSize(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:IntSize)
  }

  public interface NanoPBOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NanoPBOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * For string fields, this should include the space for null terminator.
     * </pre>
     *
     * <code>optional int32 max_size = 1;</code>
     * @return Whether the maxSize field is set.
     */
    boolean hasMaxSize();
    /**
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * For string fields, this should include the space for null terminator.
     * </pre>
     *
     * <code>optional int32 max_size = 1;</code>
     * @return The maxSize.
     */
    int getMaxSize();

    /**
     * <pre>
     * Maximum length for 'string' fields. Setting this is equivalent
     * to setting max_size to a value of length+1.
     * </pre>
     *
     * <code>optional int32 max_length = 14;</code>
     * @return Whether the maxLength field is set.
     */
    boolean hasMaxLength();
    /**
     * <pre>
     * Maximum length for 'string' fields. Setting this is equivalent
     * to setting max_size to a value of length+1.
     * </pre>
     *
     * <code>optional int32 max_length = 14;</code>
     * @return The maxLength.
     */
    int getMaxLength();

    /**
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     *
     * <code>optional int32 max_count = 2;</code>
     * @return Whether the maxCount field is set.
     */
    boolean hasMaxCount();
    /**
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     *
     * <code>optional int32 max_count = 2;</code>
     * @return The maxCount.
     */
    int getMaxCount();

    /**
     * <pre>
     * Size of integer fields. Can save some memory if you don't need
     * full 32 bits for the value.
     * </pre>
     *
     * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
     * @return Whether the intSize field is set.
     */
    boolean hasIntSize();
    /**
     * <pre>
     * Size of integer fields. Can save some memory if you don't need
     * full 32 bits for the value.
     * </pre>
     *
     * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
     * @return The intSize.
     */
    fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize getIntSize();

    /**
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     *
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     *
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     * @return The type.
     */
    fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType();

    /**
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     *
     * <code>optional bool long_names = 4 [default = true];</code>
     * @return Whether the longNames field is set.
     */
    boolean hasLongNames();
    /**
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     *
     * <code>optional bool long_names = 4 [default = true];</code>
     * @return The longNames.
     */
    boolean getLongNames();

    /**
     * <pre>
     * Add 'packed' attribute to generated structs.
     * Note: this cannot be used on CPUs that break on unaligned
     * accesses to variables.
     * </pre>
     *
     * <code>optional bool packed_struct = 5 [default = false];</code>
     * @return Whether the packedStruct field is set.
     */
    boolean hasPackedStruct();
    /**
     * <pre>
     * Add 'packed' attribute to generated structs.
     * Note: this cannot be used on CPUs that break on unaligned
     * accesses to variables.
     * </pre>
     *
     * <code>optional bool packed_struct = 5 [default = false];</code>
     * @return The packedStruct.
     */
    boolean getPackedStruct();

    /**
     * <pre>
     * Add 'packed' attribute to generated enums.
     * </pre>
     *
     * <code>optional bool packed_enum = 10 [default = false];</code>
     * @return Whether the packedEnum field is set.
     */
    boolean hasPackedEnum();
    /**
     * <pre>
     * Add 'packed' attribute to generated enums.
     * </pre>
     *
     * <code>optional bool packed_enum = 10 [default = false];</code>
     * @return The packedEnum.
     */
    boolean getPackedEnum();

    /**
     * <pre>
     * Skip this message
     * </pre>
     *
     * <code>optional bool skip_message = 6 [default = false];</code>
     * @return Whether the skipMessage field is set.
     */
    boolean hasSkipMessage();
    /**
     * <pre>
     * Skip this message
     * </pre>
     *
     * <code>optional bool skip_message = 6 [default = false];</code>
     * @return The skipMessage.
     */
    boolean getSkipMessage();

    /**
     * <pre>
     * Generate oneof fields as normal optional fields instead of union.
     * </pre>
     *
     * <code>optional bool no_unions = 8 [default = false];</code>
     * @return Whether the noUnions field is set.
     */
    boolean hasNoUnions();
    /**
     * <pre>
     * Generate oneof fields as normal optional fields instead of union.
     * </pre>
     *
     * <code>optional bool no_unions = 8 [default = false];</code>
     * @return The noUnions.
     */
    boolean getNoUnions();

    /**
     * <pre>
     * integer type tag for a message
     * </pre>
     *
     * <code>optional uint32 msgid = 9;</code>
     * @return Whether the msgid field is set.
     */
    boolean hasMsgid();
    /**
     * <pre>
     * integer type tag for a message
     * </pre>
     *
     * <code>optional uint32 msgid = 9;</code>
     * @return The msgid.
     */
    int getMsgid();

    /**
     * <pre>
     * decode oneof as anonymous union
     * </pre>
     *
     * <code>optional bool anonymous_oneof = 11 [default = false];</code>
     * @return Whether the anonymousOneof field is set.
     */
    boolean hasAnonymousOneof();
    /**
     * <pre>
     * decode oneof as anonymous union
     * </pre>
     *
     * <code>optional bool anonymous_oneof = 11 [default = false];</code>
     * @return The anonymousOneof.
     */
    boolean getAnonymousOneof();

    /**
     * <pre>
     * Proto3 singular field does not generate a "has_" flag
     * </pre>
     *
     * <code>optional bool proto3 = 12 [default = false];</code>
     * @return Whether the proto3 field is set.
     */
    boolean hasProto3();
    /**
     * <pre>
     * Proto3 singular field does not generate a "has_" flag
     * </pre>
     *
     * <code>optional bool proto3 = 12 [default = false];</code>
     * @return The proto3.
     */
    boolean getProto3();

    /**
     * <pre>
     * Generate an enum-&gt;string mapping function (can take up lots of space).
     * </pre>
     *
     * <code>optional bool enum_to_string = 13 [default = false];</code>
     * @return Whether the enumToString field is set.
     */
    boolean hasEnumToString();
    /**
     * <pre>
     * Generate an enum-&gt;string mapping function (can take up lots of space).
     * </pre>
     *
     * <code>optional bool enum_to_string = 13 [default = false];</code>
     * @return The enumToString.
     */
    boolean getEnumToString();

    /**
     * <pre>
     * Generate bytes arrays with fixed length
     * </pre>
     *
     * <code>optional bool fixed_length = 15 [default = false];</code>
     * @return Whether the fixedLength field is set.
     */
    boolean hasFixedLength();
    /**
     * <pre>
     * Generate bytes arrays with fixed length
     * </pre>
     *
     * <code>optional bool fixed_length = 15 [default = false];</code>
     * @return The fixedLength.
     */
    boolean getFixedLength();
  }
  /**
   * <pre>
   * This is the inner options message, which basically defines options for
   * a field. When it is used in message or file scope, it applies to all
   * fields.
   * </pre>
   *
   * Protobuf type {@code NanoPBOptions}
   */
  public  static final class NanoPBOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NanoPBOptions)
      NanoPBOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NanoPBOptions.newBuilder() to construct.
    private NanoPBOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NanoPBOptions() {
      intSize_ = 0;
      type_ = 0;
      longNames_ = true;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NanoPBOptions();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NanoPBOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              maxSize_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000004;
              maxCount_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType value = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                type_ = rawValue;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000020;
              longNames_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000040;
              packedStruct_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000100;
              skipMessage_ = input.readBool();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize value = fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                intSize_ = rawValue;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000200;
              noUnions_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000400;
              msgid_ = input.readUInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000080;
              packedEnum_ = input.readBool();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000800;
              anonymousOneof_ = input.readBool();
              break;
            }
            case 96: {
              bitField0_ |= 0x00001000;
              proto3_ = input.readBool();
              break;
            }
            case 104: {
              bitField0_ |= 0x00002000;
              enumToString_ = input.readBool();
              break;
            }
            case 112: {
              bitField0_ |= 0x00000002;
              maxLength_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              fixedLength_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class, fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.Builder.class);
    }

    private int bitField0_;
    public static final int MAX_SIZE_FIELD_NUMBER = 1;
    private int maxSize_;
    /**
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * For string fields, this should include the space for null terminator.
     * </pre>
     *
     * <code>optional int32 max_size = 1;</code>
     * @return Whether the maxSize field is set.
     */
    public boolean hasMaxSize() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * For string fields, this should include the space for null terminator.
     * </pre>
     *
     * <code>optional int32 max_size = 1;</code>
     * @return The maxSize.
     */
    public int getMaxSize() {
      return maxSize_;
    }

    public static final int MAX_LENGTH_FIELD_NUMBER = 14;
    private int maxLength_;
    /**
     * <pre>
     * Maximum length for 'string' fields. Setting this is equivalent
     * to setting max_size to a value of length+1.
     * </pre>
     *
     * <code>optional int32 max_length = 14;</code>
     * @return Whether the maxLength field is set.
     */
    public boolean hasMaxLength() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Maximum length for 'string' fields. Setting this is equivalent
     * to setting max_size to a value of length+1.
     * </pre>
     *
     * <code>optional int32 max_length = 14;</code>
     * @return The maxLength.
     */
    public int getMaxLength() {
      return maxLength_;
    }

    public static final int MAX_COUNT_FIELD_NUMBER = 2;
    private int maxCount_;
    /**
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     *
     * <code>optional int32 max_count = 2;</code>
     * @return Whether the maxCount field is set.
     */
    public boolean hasMaxCount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     *
     * <code>optional int32 max_count = 2;</code>
     * @return The maxCount.
     */
    public int getMaxCount() {
      return maxCount_;
    }

    public static final int INT_SIZE_FIELD_NUMBER = 7;
    private int intSize_;
    /**
     * <pre>
     * Size of integer fields. Can save some memory if you don't need
     * full 32 bits for the value.
     * </pre>
     *
     * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
     * @return Whether the intSize field is set.
     */
    public boolean hasIntSize() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Size of integer fields. Can save some memory if you don't need
     * full 32 bits for the value.
     * </pre>
     *
     * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
     * @return The intSize.
     */
    public fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize getIntSize() {
      @SuppressWarnings("deprecation")
      fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize result = fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.valueOf(intSize_);
      return result == null ? fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.IS_DEFAULT : result;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     *
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     *
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     * @return The type.
     */
    public fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType() {
      @SuppressWarnings("deprecation")
      fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType result = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.valueOf(type_);
      return result == null ? fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT : result;
    }

    public static final int LONG_NAMES_FIELD_NUMBER = 4;
    private boolean longNames_;
    /**
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     *
     * <code>optional bool long_names = 4 [default = true];</code>
     * @return Whether the longNames field is set.
     */
    public boolean hasLongNames() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     *
     * <code>optional bool long_names = 4 [default = true];</code>
     * @return The longNames.
     */
    public boolean getLongNames() {
      return longNames_;
    }

    public static final int PACKED_STRUCT_FIELD_NUMBER = 5;
    private boolean packedStruct_;
    /**
     * <pre>
     * Add 'packed' attribute to generated structs.
     * Note: this cannot be used on CPUs that break on unaligned
     * accesses to variables.
     * </pre>
     *
     * <code>optional bool packed_struct = 5 [default = false];</code>
     * @return Whether the packedStruct field is set.
     */
    public boolean hasPackedStruct() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Add 'packed' attribute to generated structs.
     * Note: this cannot be used on CPUs that break on unaligned
     * accesses to variables.
     * </pre>
     *
     * <code>optional bool packed_struct = 5 [default = false];</code>
     * @return The packedStruct.
     */
    public boolean getPackedStruct() {
      return packedStruct_;
    }

    public static final int PACKED_ENUM_FIELD_NUMBER = 10;
    private boolean packedEnum_;
    /**
     * <pre>
     * Add 'packed' attribute to generated enums.
     * </pre>
     *
     * <code>optional bool packed_enum = 10 [default = false];</code>
     * @return Whether the packedEnum field is set.
     */
    public boolean hasPackedEnum() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Add 'packed' attribute to generated enums.
     * </pre>
     *
     * <code>optional bool packed_enum = 10 [default = false];</code>
     * @return The packedEnum.
     */
    public boolean getPackedEnum() {
      return packedEnum_;
    }

    public static final int SKIP_MESSAGE_FIELD_NUMBER = 6;
    private boolean skipMessage_;
    /**
     * <pre>
     * Skip this message
     * </pre>
     *
     * <code>optional bool skip_message = 6 [default = false];</code>
     * @return Whether the skipMessage field is set.
     */
    public boolean hasSkipMessage() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * Skip this message
     * </pre>
     *
     * <code>optional bool skip_message = 6 [default = false];</code>
     * @return The skipMessage.
     */
    public boolean getSkipMessage() {
      return skipMessage_;
    }

    public static final int NO_UNIONS_FIELD_NUMBER = 8;
    private boolean noUnions_;
    /**
     * <pre>
     * Generate oneof fields as normal optional fields instead of union.
     * </pre>
     *
     * <code>optional bool no_unions = 8 [default = false];</code>
     * @return Whether the noUnions field is set.
     */
    public boolean hasNoUnions() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * Generate oneof fields as normal optional fields instead of union.
     * </pre>
     *
     * <code>optional bool no_unions = 8 [default = false];</code>
     * @return The noUnions.
     */
    public boolean getNoUnions() {
      return noUnions_;
    }

    public static final int MSGID_FIELD_NUMBER = 9;
    private int msgid_;
    /**
     * <pre>
     * integer type tag for a message
     * </pre>
     *
     * <code>optional uint32 msgid = 9;</code>
     * @return Whether the msgid field is set.
     */
    public boolean hasMsgid() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     * integer type tag for a message
     * </pre>
     *
     * <code>optional uint32 msgid = 9;</code>
     * @return The msgid.
     */
    public int getMsgid() {
      return msgid_;
    }

    public static final int ANONYMOUS_ONEOF_FIELD_NUMBER = 11;
    private boolean anonymousOneof_;
    /**
     * <pre>
     * decode oneof as anonymous union
     * </pre>
     *
     * <code>optional bool anonymous_oneof = 11 [default = false];</code>
     * @return Whether the anonymousOneof field is set.
     */
    public boolean hasAnonymousOneof() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <pre>
     * decode oneof as anonymous union
     * </pre>
     *
     * <code>optional bool anonymous_oneof = 11 [default = false];</code>
     * @return The anonymousOneof.
     */
    public boolean getAnonymousOneof() {
      return anonymousOneof_;
    }

    public static final int PROTO3_FIELD_NUMBER = 12;
    private boolean proto3_;
    /**
     * <pre>
     * Proto3 singular field does not generate a "has_" flag
     * </pre>
     *
     * <code>optional bool proto3 = 12 [default = false];</code>
     * @return Whether the proto3 field is set.
     */
    public boolean hasProto3() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <pre>
     * Proto3 singular field does not generate a "has_" flag
     * </pre>
     *
     * <code>optional bool proto3 = 12 [default = false];</code>
     * @return The proto3.
     */
    public boolean getProto3() {
      return proto3_;
    }

    public static final int ENUM_TO_STRING_FIELD_NUMBER = 13;
    private boolean enumToString_;
    /**
     * <pre>
     * Generate an enum-&gt;string mapping function (can take up lots of space).
     * </pre>
     *
     * <code>optional bool enum_to_string = 13 [default = false];</code>
     * @return Whether the enumToString field is set.
     */
    public boolean hasEnumToString() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <pre>
     * Generate an enum-&gt;string mapping function (can take up lots of space).
     * </pre>
     *
     * <code>optional bool enum_to_string = 13 [default = false];</code>
     * @return The enumToString.
     */
    public boolean getEnumToString() {
      return enumToString_;
    }

    public static final int FIXED_LENGTH_FIELD_NUMBER = 15;
    private boolean fixedLength_;
    /**
     * <pre>
     * Generate bytes arrays with fixed length
     * </pre>
     *
     * <code>optional bool fixed_length = 15 [default = false];</code>
     * @return Whether the fixedLength field is set.
     */
    public boolean hasFixedLength() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <pre>
     * Generate bytes arrays with fixed length
     * </pre>
     *
     * <code>optional bool fixed_length = 15 [default = false];</code>
     * @return The fixedLength.
     */
    public boolean getFixedLength() {
      return fixedLength_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, maxSize_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(2, maxCount_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeEnum(3, type_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(4, longNames_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBool(5, packedStruct_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeBool(6, skipMessage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(7, intSize_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeBool(8, noUnions_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeUInt32(9, msgid_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeBool(10, packedEnum_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeBool(11, anonymousOneof_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        output.writeBool(12, proto3_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        output.writeBool(13, enumToString_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(14, maxLength_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        output.writeBool(15, fixedLength_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, maxSize_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxCount_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, longNames_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, packedStruct_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, skipMessage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, intSize_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, noUnions_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, msgid_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, packedEnum_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, anonymousOneof_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, proto3_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, enumToString_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, maxLength_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, fixedLength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions)) {
        return super.equals(obj);
      }
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions other = (fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions) obj;

      if (hasMaxSize() != other.hasMaxSize()) return false;
      if (hasMaxSize()) {
        if (getMaxSize()
            != other.getMaxSize()) return false;
      }
      if (hasMaxLength() != other.hasMaxLength()) return false;
      if (hasMaxLength()) {
        if (getMaxLength()
            != other.getMaxLength()) return false;
      }
      if (hasMaxCount() != other.hasMaxCount()) return false;
      if (hasMaxCount()) {
        if (getMaxCount()
            != other.getMaxCount()) return false;
      }
      if (hasIntSize() != other.hasIntSize()) return false;
      if (hasIntSize()) {
        if (intSize_ != other.intSize_) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasLongNames() != other.hasLongNames()) return false;
      if (hasLongNames()) {
        if (getLongNames()
            != other.getLongNames()) return false;
      }
      if (hasPackedStruct() != other.hasPackedStruct()) return false;
      if (hasPackedStruct()) {
        if (getPackedStruct()
            != other.getPackedStruct()) return false;
      }
      if (hasPackedEnum() != other.hasPackedEnum()) return false;
      if (hasPackedEnum()) {
        if (getPackedEnum()
            != other.getPackedEnum()) return false;
      }
      if (hasSkipMessage() != other.hasSkipMessage()) return false;
      if (hasSkipMessage()) {
        if (getSkipMessage()
            != other.getSkipMessage()) return false;
      }
      if (hasNoUnions() != other.hasNoUnions()) return false;
      if (hasNoUnions()) {
        if (getNoUnions()
            != other.getNoUnions()) return false;
      }
      if (hasMsgid() != other.hasMsgid()) return false;
      if (hasMsgid()) {
        if (getMsgid()
            != other.getMsgid()) return false;
      }
      if (hasAnonymousOneof() != other.hasAnonymousOneof()) return false;
      if (hasAnonymousOneof()) {
        if (getAnonymousOneof()
            != other.getAnonymousOneof()) return false;
      }
      if (hasProto3() != other.hasProto3()) return false;
      if (hasProto3()) {
        if (getProto3()
            != other.getProto3()) return false;
      }
      if (hasEnumToString() != other.hasEnumToString()) return false;
      if (hasEnumToString()) {
        if (getEnumToString()
            != other.getEnumToString()) return false;
      }
      if (hasFixedLength() != other.hasFixedLength()) return false;
      if (hasFixedLength()) {
        if (getFixedLength()
            != other.getFixedLength()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMaxSize()) {
        hash = (37 * hash) + MAX_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getMaxSize();
      }
      if (hasMaxLength()) {
        hash = (37 * hash) + MAX_LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getMaxLength();
      }
      if (hasMaxCount()) {
        hash = (37 * hash) + MAX_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getMaxCount();
      }
      if (hasIntSize()) {
        hash = (37 * hash) + INT_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + intSize_;
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasLongNames()) {
        hash = (37 * hash) + LONG_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getLongNames());
      }
      if (hasPackedStruct()) {
        hash = (37 * hash) + PACKED_STRUCT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getPackedStruct());
      }
      if (hasPackedEnum()) {
        hash = (37 * hash) + PACKED_ENUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getPackedEnum());
      }
      if (hasSkipMessage()) {
        hash = (37 * hash) + SKIP_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSkipMessage());
      }
      if (hasNoUnions()) {
        hash = (37 * hash) + NO_UNIONS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNoUnions());
      }
      if (hasMsgid()) {
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgid();
      }
      if (hasAnonymousOneof()) {
        hash = (37 * hash) + ANONYMOUS_ONEOF_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAnonymousOneof());
      }
      if (hasProto3()) {
        hash = (37 * hash) + PROTO3_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getProto3());
      }
      if (hasEnumToString()) {
        hash = (37 * hash) + ENUM_TO_STRING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getEnumToString());
      }
      if (hasFixedLength()) {
        hash = (37 * hash) + FIXED_LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getFixedLength());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This is the inner options message, which basically defines options for
     * a field. When it is used in message or file scope, it applies to all
     * fields.
     * </pre>
     *
     * Protobuf type {@code NanoPBOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NanoPBOptions)
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class, fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.Builder.class);
      }

      // Construct using fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        maxSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        maxCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        intSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        longNames_ = true;
        bitField0_ = (bitField0_ & ~0x00000020);
        packedStruct_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        packedEnum_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        skipMessage_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        noUnions_ = false;
        bitField0_ = (bitField0_ & ~0x00000200);
        msgid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        anonymousOneof_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        proto3_ = false;
        bitField0_ = (bitField0_ & ~0x00001000);
        enumToString_ = false;
        bitField0_ = (bitField0_ & ~0x00002000);
        fixedLength_ = false;
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
      }

      @java.lang.Override
      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions getDefaultInstanceForType() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance();
      }

      @java.lang.Override
      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions build() {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions buildPartial() {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions result = new fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.maxSize_ = maxSize_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.maxLength_ = maxLength_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.maxCount_ = maxCount_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.intSize_ = intSize_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.longNames_ = longNames_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.packedStruct_ = packedStruct_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.packedEnum_ = packedEnum_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.skipMessage_ = skipMessage_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.noUnions_ = noUnions_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.msgid_ = msgid_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.anonymousOneof_ = anonymousOneof_;
          to_bitField0_ |= 0x00000800;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.proto3_ = proto3_;
          to_bitField0_ |= 0x00001000;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.enumToString_ = enumToString_;
          to_bitField0_ |= 0x00002000;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.fixedLength_ = fixedLength_;
          to_bitField0_ |= 0x00004000;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions) {
          return mergeFrom((fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions other) {
        if (other == fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance()) return this;
        if (other.hasMaxSize()) {
          setMaxSize(other.getMaxSize());
        }
        if (other.hasMaxLength()) {
          setMaxLength(other.getMaxLength());
        }
        if (other.hasMaxCount()) {
          setMaxCount(other.getMaxCount());
        }
        if (other.hasIntSize()) {
          setIntSize(other.getIntSize());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLongNames()) {
          setLongNames(other.getLongNames());
        }
        if (other.hasPackedStruct()) {
          setPackedStruct(other.getPackedStruct());
        }
        if (other.hasPackedEnum()) {
          setPackedEnum(other.getPackedEnum());
        }
        if (other.hasSkipMessage()) {
          setSkipMessage(other.getSkipMessage());
        }
        if (other.hasNoUnions()) {
          setNoUnions(other.getNoUnions());
        }
        if (other.hasMsgid()) {
          setMsgid(other.getMsgid());
        }
        if (other.hasAnonymousOneof()) {
          setAnonymousOneof(other.getAnonymousOneof());
        }
        if (other.hasProto3()) {
          setProto3(other.getProto3());
        }
        if (other.hasEnumToString()) {
          setEnumToString(other.getEnumToString());
        }
        if (other.hasFixedLength()) {
          setFixedLength(other.getFixedLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int maxSize_ ;
      /**
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * For string fields, this should include the space for null terminator.
       * </pre>
       *
       * <code>optional int32 max_size = 1;</code>
       * @return Whether the maxSize field is set.
       */
      public boolean hasMaxSize() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * For string fields, this should include the space for null terminator.
       * </pre>
       *
       * <code>optional int32 max_size = 1;</code>
       * @return The maxSize.
       */
      public int getMaxSize() {
        return maxSize_;
      }
      /**
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * For string fields, this should include the space for null terminator.
       * </pre>
       *
       * <code>optional int32 max_size = 1;</code>
       * @param value The maxSize to set.
       * @return This builder for chaining.
       */
      public Builder setMaxSize(int value) {
        bitField0_ |= 0x00000001;
        maxSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * For string fields, this should include the space for null terminator.
       * </pre>
       *
       * <code>optional int32 max_size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxSize_ = 0;
        onChanged();
        return this;
      }

      private int maxLength_ ;
      /**
       * <pre>
       * Maximum length for 'string' fields. Setting this is equivalent
       * to setting max_size to a value of length+1.
       * </pre>
       *
       * <code>optional int32 max_length = 14;</code>
       * @return Whether the maxLength field is set.
       */
      public boolean hasMaxLength() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Maximum length for 'string' fields. Setting this is equivalent
       * to setting max_size to a value of length+1.
       * </pre>
       *
       * <code>optional int32 max_length = 14;</code>
       * @return The maxLength.
       */
      public int getMaxLength() {
        return maxLength_;
      }
      /**
       * <pre>
       * Maximum length for 'string' fields. Setting this is equivalent
       * to setting max_size to a value of length+1.
       * </pre>
       *
       * <code>optional int32 max_length = 14;</code>
       * @param value The maxLength to set.
       * @return This builder for chaining.
       */
      public Builder setMaxLength(int value) {
        bitField0_ |= 0x00000002;
        maxLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Maximum length for 'string' fields. Setting this is equivalent
       * to setting max_size to a value of length+1.
       * </pre>
       *
       * <code>optional int32 max_length = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxLength_ = 0;
        onChanged();
        return this;
      }

      private int maxCount_ ;
      /**
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       *
       * <code>optional int32 max_count = 2;</code>
       * @return Whether the maxCount field is set.
       */
      public boolean hasMaxCount() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       *
       * <code>optional int32 max_count = 2;</code>
       * @return The maxCount.
       */
      public int getMaxCount() {
        return maxCount_;
      }
      /**
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       *
       * <code>optional int32 max_count = 2;</code>
       * @param value The maxCount to set.
       * @return This builder for chaining.
       */
      public Builder setMaxCount(int value) {
        bitField0_ |= 0x00000004;
        maxCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       *
       * <code>optional int32 max_count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxCount_ = 0;
        onChanged();
        return this;
      }

      private int intSize_ = 0;
      /**
       * <pre>
       * Size of integer fields. Can save some memory if you don't need
       * full 32 bits for the value.
       * </pre>
       *
       * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
       * @return Whether the intSize field is set.
       */
      public boolean hasIntSize() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Size of integer fields. Can save some memory if you don't need
       * full 32 bits for the value.
       * </pre>
       *
       * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
       * @return The intSize.
       */
      public fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize getIntSize() {
        @SuppressWarnings("deprecation")
        fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize result = fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.valueOf(intSize_);
        return result == null ? fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.IS_DEFAULT : result;
      }
      /**
       * <pre>
       * Size of integer fields. Can save some memory if you don't need
       * full 32 bits for the value.
       * </pre>
       *
       * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
       * @param value The intSize to set.
       * @return This builder for chaining.
       */
      public Builder setIntSize(fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        intSize_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Size of integer fields. Can save some memory if you don't need
       * full 32 bits for the value.
       * </pre>
       *
       * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
       * @return This builder for chaining.
       */
      public Builder clearIntSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        intSize_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       *
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       *
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       * @return The type.
       */
      public fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType() {
        @SuppressWarnings("deprecation")
        fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType result = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.valueOf(type_);
        return result == null ? fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT : result;
      }
      /**
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       *
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       *
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        onChanged();
        return this;
      }

      private boolean longNames_ = true;
      /**
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       *
       * <code>optional bool long_names = 4 [default = true];</code>
       * @return Whether the longNames field is set.
       */
      public boolean hasLongNames() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       *
       * <code>optional bool long_names = 4 [default = true];</code>
       * @return The longNames.
       */
      public boolean getLongNames() {
        return longNames_;
      }
      /**
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       *
       * <code>optional bool long_names = 4 [default = true];</code>
       * @param value The longNames to set.
       * @return This builder for chaining.
       */
      public Builder setLongNames(boolean value) {
        bitField0_ |= 0x00000020;
        longNames_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       *
       * <code>optional bool long_names = 4 [default = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearLongNames() {
        bitField0_ = (bitField0_ & ~0x00000020);
        longNames_ = true;
        onChanged();
        return this;
      }

      private boolean packedStruct_ ;
      /**
       * <pre>
       * Add 'packed' attribute to generated structs.
       * Note: this cannot be used on CPUs that break on unaligned
       * accesses to variables.
       * </pre>
       *
       * <code>optional bool packed_struct = 5 [default = false];</code>
       * @return Whether the packedStruct field is set.
       */
      public boolean hasPackedStruct() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * Add 'packed' attribute to generated structs.
       * Note: this cannot be used on CPUs that break on unaligned
       * accesses to variables.
       * </pre>
       *
       * <code>optional bool packed_struct = 5 [default = false];</code>
       * @return The packedStruct.
       */
      public boolean getPackedStruct() {
        return packedStruct_;
      }
      /**
       * <pre>
       * Add 'packed' attribute to generated structs.
       * Note: this cannot be used on CPUs that break on unaligned
       * accesses to variables.
       * </pre>
       *
       * <code>optional bool packed_struct = 5 [default = false];</code>
       * @param value The packedStruct to set.
       * @return This builder for chaining.
       */
      public Builder setPackedStruct(boolean value) {
        bitField0_ |= 0x00000040;
        packedStruct_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Add 'packed' attribute to generated structs.
       * Note: this cannot be used on CPUs that break on unaligned
       * accesses to variables.
       * </pre>
       *
       * <code>optional bool packed_struct = 5 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearPackedStruct() {
        bitField0_ = (bitField0_ & ~0x00000040);
        packedStruct_ = false;
        onChanged();
        return this;
      }

      private boolean packedEnum_ ;
      /**
       * <pre>
       * Add 'packed' attribute to generated enums.
       * </pre>
       *
       * <code>optional bool packed_enum = 10 [default = false];</code>
       * @return Whether the packedEnum field is set.
       */
      public boolean hasPackedEnum() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * Add 'packed' attribute to generated enums.
       * </pre>
       *
       * <code>optional bool packed_enum = 10 [default = false];</code>
       * @return The packedEnum.
       */
      public boolean getPackedEnum() {
        return packedEnum_;
      }
      /**
       * <pre>
       * Add 'packed' attribute to generated enums.
       * </pre>
       *
       * <code>optional bool packed_enum = 10 [default = false];</code>
       * @param value The packedEnum to set.
       * @return This builder for chaining.
       */
      public Builder setPackedEnum(boolean value) {
        bitField0_ |= 0x00000080;
        packedEnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Add 'packed' attribute to generated enums.
       * </pre>
       *
       * <code>optional bool packed_enum = 10 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearPackedEnum() {
        bitField0_ = (bitField0_ & ~0x00000080);
        packedEnum_ = false;
        onChanged();
        return this;
      }

      private boolean skipMessage_ ;
      /**
       * <pre>
       * Skip this message
       * </pre>
       *
       * <code>optional bool skip_message = 6 [default = false];</code>
       * @return Whether the skipMessage field is set.
       */
      public boolean hasSkipMessage() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       * Skip this message
       * </pre>
       *
       * <code>optional bool skip_message = 6 [default = false];</code>
       * @return The skipMessage.
       */
      public boolean getSkipMessage() {
        return skipMessage_;
      }
      /**
       * <pre>
       * Skip this message
       * </pre>
       *
       * <code>optional bool skip_message = 6 [default = false];</code>
       * @param value The skipMessage to set.
       * @return This builder for chaining.
       */
      public Builder setSkipMessage(boolean value) {
        bitField0_ |= 0x00000100;
        skipMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Skip this message
       * </pre>
       *
       * <code>optional bool skip_message = 6 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearSkipMessage() {
        bitField0_ = (bitField0_ & ~0x00000100);
        skipMessage_ = false;
        onChanged();
        return this;
      }

      private boolean noUnions_ ;
      /**
       * <pre>
       * Generate oneof fields as normal optional fields instead of union.
       * </pre>
       *
       * <code>optional bool no_unions = 8 [default = false];</code>
       * @return Whether the noUnions field is set.
       */
      public boolean hasNoUnions() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <pre>
       * Generate oneof fields as normal optional fields instead of union.
       * </pre>
       *
       * <code>optional bool no_unions = 8 [default = false];</code>
       * @return The noUnions.
       */
      public boolean getNoUnions() {
        return noUnions_;
      }
      /**
       * <pre>
       * Generate oneof fields as normal optional fields instead of union.
       * </pre>
       *
       * <code>optional bool no_unions = 8 [default = false];</code>
       * @param value The noUnions to set.
       * @return This builder for chaining.
       */
      public Builder setNoUnions(boolean value) {
        bitField0_ |= 0x00000200;
        noUnions_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Generate oneof fields as normal optional fields instead of union.
       * </pre>
       *
       * <code>optional bool no_unions = 8 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearNoUnions() {
        bitField0_ = (bitField0_ & ~0x00000200);
        noUnions_ = false;
        onChanged();
        return this;
      }

      private int msgid_ ;
      /**
       * <pre>
       * integer type tag for a message
       * </pre>
       *
       * <code>optional uint32 msgid = 9;</code>
       * @return Whether the msgid field is set.
       */
      public boolean hasMsgid() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <pre>
       * integer type tag for a message
       * </pre>
       *
       * <code>optional uint32 msgid = 9;</code>
       * @return The msgid.
       */
      public int getMsgid() {
        return msgid_;
      }
      /**
       * <pre>
       * integer type tag for a message
       * </pre>
       *
       * <code>optional uint32 msgid = 9;</code>
       * @param value The msgid to set.
       * @return This builder for chaining.
       */
      public Builder setMsgid(int value) {
        bitField0_ |= 0x00000400;
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * integer type tag for a message
       * </pre>
       *
       * <code>optional uint32 msgid = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgid() {
        bitField0_ = (bitField0_ & ~0x00000400);
        msgid_ = 0;
        onChanged();
        return this;
      }

      private boolean anonymousOneof_ ;
      /**
       * <pre>
       * decode oneof as anonymous union
       * </pre>
       *
       * <code>optional bool anonymous_oneof = 11 [default = false];</code>
       * @return Whether the anonymousOneof field is set.
       */
      public boolean hasAnonymousOneof() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <pre>
       * decode oneof as anonymous union
       * </pre>
       *
       * <code>optional bool anonymous_oneof = 11 [default = false];</code>
       * @return The anonymousOneof.
       */
      public boolean getAnonymousOneof() {
        return anonymousOneof_;
      }
      /**
       * <pre>
       * decode oneof as anonymous union
       * </pre>
       *
       * <code>optional bool anonymous_oneof = 11 [default = false];</code>
       * @param value The anonymousOneof to set.
       * @return This builder for chaining.
       */
      public Builder setAnonymousOneof(boolean value) {
        bitField0_ |= 0x00000800;
        anonymousOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * decode oneof as anonymous union
       * </pre>
       *
       * <code>optional bool anonymous_oneof = 11 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearAnonymousOneof() {
        bitField0_ = (bitField0_ & ~0x00000800);
        anonymousOneof_ = false;
        onChanged();
        return this;
      }

      private boolean proto3_ ;
      /**
       * <pre>
       * Proto3 singular field does not generate a "has_" flag
       * </pre>
       *
       * <code>optional bool proto3 = 12 [default = false];</code>
       * @return Whether the proto3 field is set.
       */
      public boolean hasProto3() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <pre>
       * Proto3 singular field does not generate a "has_" flag
       * </pre>
       *
       * <code>optional bool proto3 = 12 [default = false];</code>
       * @return The proto3.
       */
      public boolean getProto3() {
        return proto3_;
      }
      /**
       * <pre>
       * Proto3 singular field does not generate a "has_" flag
       * </pre>
       *
       * <code>optional bool proto3 = 12 [default = false];</code>
       * @param value The proto3 to set.
       * @return This builder for chaining.
       */
      public Builder setProto3(boolean value) {
        bitField0_ |= 0x00001000;
        proto3_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Proto3 singular field does not generate a "has_" flag
       * </pre>
       *
       * <code>optional bool proto3 = 12 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearProto3() {
        bitField0_ = (bitField0_ & ~0x00001000);
        proto3_ = false;
        onChanged();
        return this;
      }

      private boolean enumToString_ ;
      /**
       * <pre>
       * Generate an enum-&gt;string mapping function (can take up lots of space).
       * </pre>
       *
       * <code>optional bool enum_to_string = 13 [default = false];</code>
       * @return Whether the enumToString field is set.
       */
      public boolean hasEnumToString() {
        return ((bitField0_ & 0x00002000) != 0);
      }
      /**
       * <pre>
       * Generate an enum-&gt;string mapping function (can take up lots of space).
       * </pre>
       *
       * <code>optional bool enum_to_string = 13 [default = false];</code>
       * @return The enumToString.
       */
      public boolean getEnumToString() {
        return enumToString_;
      }
      /**
       * <pre>
       * Generate an enum-&gt;string mapping function (can take up lots of space).
       * </pre>
       *
       * <code>optional bool enum_to_string = 13 [default = false];</code>
       * @param value The enumToString to set.
       * @return This builder for chaining.
       */
      public Builder setEnumToString(boolean value) {
        bitField0_ |= 0x00002000;
        enumToString_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Generate an enum-&gt;string mapping function (can take up lots of space).
       * </pre>
       *
       * <code>optional bool enum_to_string = 13 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearEnumToString() {
        bitField0_ = (bitField0_ & ~0x00002000);
        enumToString_ = false;
        onChanged();
        return this;
      }

      private boolean fixedLength_ ;
      /**
       * <pre>
       * Generate bytes arrays with fixed length
       * </pre>
       *
       * <code>optional bool fixed_length = 15 [default = false];</code>
       * @return Whether the fixedLength field is set.
       */
      public boolean hasFixedLength() {
        return ((bitField0_ & 0x00004000) != 0);
      }
      /**
       * <pre>
       * Generate bytes arrays with fixed length
       * </pre>
       *
       * <code>optional bool fixed_length = 15 [default = false];</code>
       * @return The fixedLength.
       */
      public boolean getFixedLength() {
        return fixedLength_;
      }
      /**
       * <pre>
       * Generate bytes arrays with fixed length
       * </pre>
       *
       * <code>optional bool fixed_length = 15 [default = false];</code>
       * @param value The fixedLength to set.
       * @return This builder for chaining.
       */
      public Builder setFixedLength(boolean value) {
        bitField0_ |= 0x00004000;
        fixedLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Generate bytes arrays with fixed length
       * </pre>
       *
       * <code>optional bool fixed_length = 15 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearFixedLength() {
        bitField0_ = (bitField0_ & ~0x00004000);
        fixedLength_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NanoPBOptions)
    }

    // @@protoc_insertion_point(class_scope:NanoPBOptions)
    private static final fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions();
    }

    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NanoPBOptions>
        PARSER = new com.google.protobuf.AbstractParser<NanoPBOptions>() {
      @java.lang.Override
      public NanoPBOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NanoPBOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NanoPBOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NanoPBOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NANOPB_FILEOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbFileopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_MSGOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbMsgopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_ENUMOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbEnumopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopb = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NanoPBOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NanoPBOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014nanopb.proto\032 google/protobuf/descript" +
      "or.proto\"\243\003\n\rNanoPBOptions\022\020\n\010max_size\030\001" +
      " \001(\005\022\022\n\nmax_length\030\016 \001(\005\022\021\n\tmax_count\030\002 " +
      "\001(\005\022&\n\010int_size\030\007 \001(\0162\010.IntSize:\nIS_DEFA" +
      "ULT\022$\n\004type\030\003 \001(\0162\n.FieldType:\nFT_DEFAUL" +
      "T\022\030\n\nlong_names\030\004 \001(\010:\004true\022\034\n\rpacked_st" +
      "ruct\030\005 \001(\010:\005false\022\032\n\013packed_enum\030\n \001(\010:\005" +
      "false\022\033\n\014skip_message\030\006 \001(\010:\005false\022\030\n\tno" +
      "_unions\030\010 \001(\010:\005false\022\r\n\005msgid\030\t \001(\r\022\036\n\017a" +
      "nonymous_oneof\030\013 \001(\010:\005false\022\025\n\006proto3\030\014 " +
      "\001(\010:\005false\022\035\n\016enum_to_string\030\r \001(\010:\005fals" +
      "e\022\033\n\014fixed_length\030\017 \001(\010:\005false*i\n\tFieldT" +
      "ype\022\016\n\nFT_DEFAULT\020\000\022\017\n\013FT_CALLBACK\020\001\022\016\n\n" +
      "FT_POINTER\020\004\022\r\n\tFT_STATIC\020\002\022\r\n\tFT_IGNORE" +
      "\020\003\022\r\n\tFT_INLINE\020\005*D\n\007IntSize\022\016\n\nIS_DEFAU" +
      "LT\020\000\022\010\n\004IS_8\020\010\022\t\n\005IS_16\020\020\022\t\n\005IS_32\020 \022\t\n\005" +
      "IS_64\020@:E\n\016nanopb_fileopt\022\034.google.proto" +
      "buf.FileOptions\030\362\007 \001(\0132\016.NanoPBOptions:G" +
      "\n\rnanopb_msgopt\022\037.google.protobuf.Messag" +
      "eOptions\030\362\007 \001(\0132\016.NanoPBOptions:E\n\016nanop" +
      "b_enumopt\022\034.google.protobuf.EnumOptions\030" +
      "\362\007 \001(\0132\016.NanoPBOptions:>\n\006nanopb\022\035.googl" +
      "e.protobuf.FieldOptions\030\362\007 \001(\0132\016.NanoPBO" +
      "ptionsB\032\n\030fi.kapsi.koti.jpa.nanopb"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_NanoPBOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NanoPBOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NanoPBOptions_descriptor,
        new java.lang.String[] { "MaxSize", "MaxLength", "MaxCount", "IntSize", "Type", "LongNames", "PackedStruct", "PackedEnum", "SkipMessage", "NoUnions", "Msgid", "AnonymousOneof", "Proto3", "EnumToString", "FixedLength", });
    nanopbFileopt.internalInit(descriptor.getExtensions().get(0));
    nanopbMsgopt.internalInit(descriptor.getExtensions().get(1));
    nanopbEnumopt.internalInit(descriptor.getExtensions().get(2));
    nanopb.internalInit(descriptor.getExtensions().get(3));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
