/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mqttfx.wirepas.decoder;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;

import de.jensd.addon.decoder.AbstractPayloadDecoder;
import com.wirepas.wpe.Public.Node;


public class WirepasWPEProtobufDecoder extends AbstractPayloadDecoder {

	/**
	 * Constructor.
	 */
	public WirepasWPEProtobufDecoder() {
		super();
	}

	@Override
	public String getName() {
		return "Wirepas WPE Protobuf decoder";
	}

	@Override
	public String getId() {
		return "wp_wpe_protobuf_decoder";
	}

	@Override
	public String getVersion() {
		return "1.1";
	}

	@Override
	public String getDescription() {
		return "Decode Wirepas WPE protobuf into JSON format";
	}

	@Override
	public String decode(byte[] payload) {
		String result;
		
		try {
			Node NodeMessage = Node.parseFrom(payload);
			result = JsonFormat.printer().print(NodeMessage);
		} catch (InvalidProtocolBufferException e) {
			result = "*** PAYLOAD IS NOT VALID WIREPAS PROTOBUF DATA *** \n\n";
		}
		
		return result;
	}
}