/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mqttfx.wirepas.decoder;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;

import de.jensd.addon.decoder.AbstractPayloadDecoder;
import wirepas.proto.gateway_api.GenericMessageOuterClass.GenericMessage;

public class WirepasProtobufDecoder extends AbstractPayloadDecoder {

	/**
	 * Constructor.
	 */
	public WirepasProtobufDecoder() {
		super();
	}

	@Override
	public String getName() {
		return "Wirepas Generic Protobuf decoder";
	}

	@Override
	public String getId() {
		return "wp_protobuf_decoder";
	}

	@Override
	public String getVersion() {
		return "1.0";
	}

	@Override
	public String getDescription() {
		return "Decode Wirepas protobuf into JSON format";
	}

	@Override
	public String decode(byte[] payload) {
		String result;
		
		try {
			GenericMessage genMessage = GenericMessage.parseFrom(payload);
			result = JsonFormat.printer().print(genMessage);
		} catch (InvalidProtocolBufferException e) {
			result = "*** PAYLOAD IS NOT VALID WIREPAS PROTOBUF DATA *** \n\n";
		}
		
		return result;
	}
}
